sh_binary(
    name = "simctl",
    srcs = ["simctl.sh"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "verilator",
    srcs = ["verilator.sh"],
    visibility = ["//visibility:public"],
)
